# Generated by Django 3.1.7 on 2021-03-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0005_auto_20210303_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='coordinate',
            field=models.TextField(),
        ),
    ]
