# Generated by Django 3.1.7 on 2021-03-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0006_auto_20210307_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='square_ha',
            field=models.PositiveIntegerField(default=1, verbose_name='Площадь поля в гектарах'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='square',
            field=models.PositiveIntegerField(verbose_name='Площадь поля в квадратных метрах'),
        ),
    ]
