# Generated by Django 3.1.7 on 2021-03-31 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0007_auto_20210309_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128, verbose_name='Наименование работы')),
            ],
            options={
                'verbose_name': 'Наименование работы',
                'verbose_name_plural': 'Наименование работ',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=32, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'unique_together': {('firstname', 'lastname')},
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_job', models.DateTimeField(verbose_name='Начало работы')),
                ('end_job', models.DateTimeField(verbose_name='Конец работы')),
                ('comment', models.TextField(verbose_name='Комментарии')),
                ('status', models.CharField(choices=[('ED', 'Ожидается'), ('PD', 'Выполняется'), ('CD', 'Завершено')], default='ED', max_length=32)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.jobcategory', verbose_name='Наименование работы')),
                ('fields', models.ManyToManyField(to='fields.Field', verbose_name='Список полей')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.season', verbose_name='Сезон')),
                ('workers', models.ManyToManyField(to='fields.Worker', verbose_name='Исполнители')),
            ],
        ),
    ]
