# Generated by Django 3.1.7 on 2021-05-01 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0010_auto_20210501_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='end_job',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Конец работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='start_job',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало работы'),
            preserve_default=False,
        ),
    ]
