# Generated by Django 3.1.7 on 2021-05-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0011_auto_20210501_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='square_ha',
            field=models.PositiveIntegerField(verbose_name='Площадь поля в гектарах'),
        ),
    ]
