# Generated by Django 3.1.7 on 2021-05-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0013_auto_20210509_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
    ]
